language: go
sudo: required
addons:
  apt:
    packages:
      - aspell
      - aspell-en
go:
  - master # This uses automatically the latest version of go

install:
  # - go get github.com/gohugoio/hugo
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.deb # how can we get to update automatically?
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo --theme=casper-custom # This commands builds your website on travis
  - ./bin/check_spelling.sh

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: samus-aran/samus-aran.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_RESOURCE # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: ashjayne.nicolson@gmail.com
  name: "samus-aran"
  on:
    branch: master